// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlja153xGpSppQwd9Lv7dfnUUBclBo65c',
    appId: '1:370655328947:android:63dda593b4b96aa98c0ec6',
    messagingSenderId: '370655328947',
    projectId: 'bliper-8acab',
    storageBucket: 'bliper-8acab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIKlP5iYHjcxIl2TavvDXGx43U9MnqdaM',
    appId: '1:370655328947:ios:210ca1c2ed3333398c0ec6',
    messagingSenderId: '370655328947',
    projectId: 'bliper-8acab',
    storageBucket: 'bliper-8acab.appspot.com',
    androidClientId: '370655328947-qlrs5jniuvaldursvac1doarc6cn92cb.apps.googleusercontent.com',
    iosClientId: '370655328947-g2vjudqj7c0fn496ihv87q23r91165kc.apps.googleusercontent.com',
    iosBundleId: 'com.blipermesero.bliperMesero',
  );
}
